server:
  port: 8080

abatis:
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/idea?useSSL=false&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
  username: root
  password: andyadc
  mapperLocations: classpath*:mapper/*.xml
  base-mapper-package: com.andyadc.starter.abatis.test.mapper